[engine]
cgroup_manager = "cgroupfs"
events_logger = "file"
helper_binaries_dir = [
    "/var/lib/easyenclave/bin/podman-linux-amd64/usr/local/lib/podman",
    "/var/lib/easyenclave/bin/podman-linux-amd64/usr/local/bin"
]
