[engine]
cgroup_manager = "cgroupfs"
events_logger = "file"
static_dir = "/var/lib/easyenclave/containers/storage/libpod"
tmp_dir = "/run/libpod"
volume_path = "/var/lib/easyenclave/containers/storage/volumes"
helper_binaries_dir = [
    "/var/lib/easyenclave/bin/podman-linux-amd64/usr/local/lib/podman",
    "/var/lib/easyenclave/bin/podman-linux-amd64/usr/local/bin"
]
